spring.application.name=MinhaAPI

spring.datasource.url=jdbc:postgresql://localhost:5433/filmes
spring.datasource.username=postgres
spring.datasource.password=221098

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
